version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Run Kafka with SASL_SSL and PLAINTEXT listeners
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - 29092:29092
      - 29093:29093
    depends_on:
      - zookeeper
    environment:
      # Zookeeper
      ZOOKEEPER_SASL_ENABLED: "false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # General
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      # Listeners
      # Run SASL_SSL on port 29092 and PLAINTEXT on port 29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_SSL:SASL_SSL,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: SASL_SSL://:29092,PLAINTEXT://:29093
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL://kafka:29092,PLAINTEXT://kafka:29093

      # SASL
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/jaas.conf

      # SSL
      KAFKA_SSL_KEYSTORE_FILENAME: keystore.jks
      KAFKA_SSL_TRUSTSTORE_FILENAME: keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: creds
      KAFKA_SSL_KEY_CREDENTIALS: creds
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: creds

    volumes:
      - ./secrets:/etc/kafka/secrets
