openapi: "3.0.3"
info:
  title: "Anchor Platform Admin Server"
  description: "The Anchor Platform Admin Server."
  version: "3.0.0"
servers:
  - url: "http://0.0.0.0:8080"
paths:
  /configurations:
    get:
      description: "Get all configurations"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "string"
components:
  schemas: { }