name: Gradle Build and Test

on:
  # allows this workflow to be called from another workflow
  workflow_dispatch:
  workflow_call:

jobs:
  gradle_test_and_build:
    name: Gradle Test and Build
    runs-on: ubuntu-latest-16-cores
    # write to PR  permission is required for jacocoTestReport Action to update comment
    permissions:
      contents: read
      pull-requests: write
    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # This is to add to DNS entries to access the services started by docker-compose.
      # This should be deprecated. Refer to: https://stackoverflow.com/questions/47762339/how-to-correctly-set-up-docker-network-to-use-localhost-connection/47763442#47763442
      - name: Set up hostnames (/etc/hosts)
        run: |
          sudo echo "127.0.0.1 db" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 zookeeper" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 kafka" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 sep24-reference-ui" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 reference-server" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 wallet-server" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 platform" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 custody-server" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 host.docker.internal" | sudo tee -a /etc/hosts 

      - name: Run pwd
        run: echo `pwd`

      - name: Error here
        run: curl --fail -o dates.csv https://doesnotexist.com/dates.csv
        continue-on-error: false

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: gradle-artifact
          path: /etc/hosts

